INSERT INTO Source (idSource, nameSource, aliasSource) VALUES (1, 'NieR:Automata', 'Nier');
INSERT INTO Source (idSource, nameSource, aliasSource) VALUES (2, 'Machikado Mazoku', null);
INSERT INTO Source (idSource, nameSource, aliasSource) VALUES (3, 'Maou-jou de Oyasumi ', null);
INSERT INTO Source (idSource, nameSource, aliasSource) VALUES (4, 'Tonikaku Kawaii ', 'Tonikawa');
INSERT INTO Source (idSource, nameSource, aliasSource) VALUES (5, 'Kobayashi-san Chi no Maidragon ', 'Maidragon');
INSERT INTO Source (idSource, nameSource, aliasSource) VALUES (6, 'Kono Subarashii Sekai ni Shukufuku wo!', 'Konosuba');
INSERT INTO Source (idSource, nameSource, aliasSource) VALUES (7, 'Watashi ni Tenshi ga Maiorita!', 'Wataten');
INSERT INTO Source (idSource, nameSource, aliasSource) VALUES (8, 'Chuunibyou demo Koi ga Shitai!', 'Chuunibyou');
INSERT INTO Source (idSource, nameSource, aliasSource) VALUES (9, 'Horimiya', null);
INSERT INTO Source (idSource, nameSource, aliasSource) VALUES (10, 'JoJo no Kimyou na Bouken', 'JoJo');
INSERT INTO Source (idSource, nameSource, aliasSource) VALUES (11, 'Kaguya-sama wa Kokurasetai: Tensai-tachi no Renai Zunousen ', 'Kaguya-sama');
INSERT INTO Source (idSource, nameSource, aliasSource) VALUES (12, 'Re:Zero kara Hajimeru Isekai Seikatsu', 'ReZero');
INSERT INTO Source (idSource, nameSource, aliasSource) VALUES (13, 'Ookami to Koushinryou', 'Spice and Wolf');
INSERT INTO Source (idSource, nameSource, aliasSource) VALUES (14, 'No Game No Life', 'NGNL');
INSERT INTO Source (idSource, nameSource, aliasSource) VALUES (17, 'Haiyore! Nyaruko-san', null);
INSERT INTO Source (idSource, nameSource, aliasSource) VALUES (24, 'Steins;Gate', null);
INSERT INTO Source (idSource, nameSource, aliasSource) VALUES (25, 'Darling in the Franxx', null);

INSERT INTO Waifu (idWaifu, nameWaifu, nickWaifu, tierWaifu, imageURLWaifu, User_idUser, Source_idSource) VALUES (1, 'YoRHa No.2 Type B', '2B', 6, 'https://s4.anilist.co/file/anilistcdn/character/large/b132494-uAR64S686x4Q.png', null, 1);
INSERT INTO Waifu (idWaifu, nameWaifu, nickWaifu, tierWaifu, imageURLWaifu, User_idUser, Source_idSource) VALUES (2, 'YoRHa No.2 Type A', 'A2', 1, 'https://s4.anilist.co/file/anilistcdn/character/large/b138298-3WByYu03g417.jpg', null, 1);
INSERT INTO Waifu (idWaifu, nameWaifu, nickWaifu, tierWaifu, imageURLWaifu, User_idUser, Source_idSource) VALUES (3, 'Yuuko Yoshida', 'Shamiko', 1, 'https://s4.anilist.co/file/anilistcdn/character/large/b141461-5ZkxFDzP408S.png', null, 2);
INSERT INTO Waifu (idWaifu, nameWaifu, nickWaifu, tierWaifu, imageURLWaifu, User_idUser, Source_idSource) VALUES (4, 'Momo Chiyoda', 'Chiyomomo', 1, 'https://s4.anilist.co/file/anilistcdn/character/large/b141457-zbvICmxe7kgM.png', null, 2);
INSERT INTO Waifu (idWaifu, nameWaifu, nickWaifu, tierWaifu, imageURLWaifu, User_idUser, Source_idSource) VALUES (5, 'Aurora Suya Rhys Kaymin', 'Princess Syalis', 1, 'https://s4.anilist.co/file/anilistcdn/character/large/b129563-gvB1zh25unS0.png', null, 3);
INSERT INTO Waifu (idWaifu, nameWaifu, nickWaifu, tierWaifu, imageURLWaifu, User_idUser, Source_idSource) VALUES (6, 'Miss Kobayashi', 'Kobayashi', 1, 'https://s4.anilist.co/file/anilistcdn/character/large/120969-b1kIfJv9kVzW.jpg', null, 5);
INSERT INTO Waifu (idWaifu, nameWaifu, nickWaifu, tierWaifu, imageURLWaifu, User_idUser, Source_idSource) VALUES (7, 'Tohru', null, 1, 'https://s4.anilist.co/file/anilistcdn/character/large/b120970-knjWLdlQIs1y.jpg', null, 5);
INSERT INTO Waifu (idWaifu, nameWaifu, nickWaifu, tierWaifu, imageURLWaifu, User_idUser, Source_idSource) VALUES (8, 'Kanna Kamui', 'Kanna', 6, 'https://s4.anilist.co/file/anilistcdn/character/large/b120974-7XjGb1MLvEZl.jpg', null, 5);
INSERT INTO Waifu (idWaifu, nameWaifu, nickWaifu, tierWaifu, imageURLWaifu, User_idUser, Source_idSource) VALUES (9, 'Megumin', 'Explosion loli', 6, 'https://s4.anilist.co/file/anilistcdn/character/large/b89361-x71P6YLrndd8.png', null, 6);
INSERT INTO Waifu (idWaifu, nameWaifu, nickWaifu, tierWaifu, imageURLWaifu, User_idUser, Source_idSource) VALUES (10, 'Aqua', 'Useless', 1, 'https://s4.anilist.co/file/anilistcdn/character/large/b89362-ibkc0eoECaW1.png', null, 6);
INSERT INTO Waifu (idWaifu, nameWaifu, nickWaifu, tierWaifu, imageURLWaifu, User_idUser, Source_idSource) VALUES (11, 'Dustiness Ford Lalatina', 'Darkness', 1, 'https://s4.anilist.co/file/anilistcdn/character/large/b89363-mm21Ll4NegUD.png', null, 6);
INSERT INTO Waifu (idWaifu, nameWaifu, nickWaifu, tierWaifu, imageURLWaifu, User_idUser, Source_idSource) VALUES (12, 'Yunyun', null, 1, 'https://s4.anilist.co/file/anilistcdn/character/large/b120652-YxrBBPbmJno2.png', null, 6);
INSERT INTO Waifu (idWaifu, nameWaifu, nickWaifu, tierWaifu, imageURLWaifu, User_idUser, Source_idSource) VALUES (13, 'Wiz', null, 1, 'https://s4.anilist.co/file/anilistcdn/character/large/120655-MN3fgTk7bucp.jpg', null, 6);
INSERT INTO Waifu (idWaifu, nameWaifu, nickWaifu, tierWaifu, imageURLWaifu, User_idUser, Source_idSource) VALUES (14, 'Miyako Hoshino', 'Mya-nee', 1, 'https://s4.anilist.co/file/anilistcdn/character/large/b131475-ceIIo9488FVn.png', null, 7);
INSERT INTO Waifu (idWaifu, nameWaifu, nickWaifu, tierWaifu, imageURLWaifu, User_idUser, Source_idSource) VALUES (15, 'Kouko Matsumoto', null, 1, 'https://s4.anilist.co/file/anilistcdn/character/large/b136814-13l67fUbiWWz.jpg', null, 7);
INSERT INTO Waifu (idWaifu, nameWaifu, nickWaifu, tierWaifu, imageURLWaifu, User_idUser, Source_idSource) VALUES (16, 'Rikka Takanashi', 'Wielder of Tyrant''s Eye', 1, 'https://s4.anilist.co/file/anilistcdn/character/large/b65865-ApBBSvSOIee2.jpg', null, 8);
INSERT INTO Waifu (idWaifu, nameWaifu, nickWaifu, tierWaifu, imageURLWaifu, User_idUser, Source_idSource) VALUES (17, 'Kyouko Hori', 'Hori-san', 6, 'https://s4.anilist.co/file/anilistcdn/character/large/b66171-o2vk3689wWFK.png', null, 9);
INSERT INTO Waifu (idWaifu, nameWaifu, nickWaifu, tierWaifu, imageURLWaifu, User_idUser, Source_idSource) VALUES (18, 'Robert E. O. Speedwagon', 'Speedwagon', 1, 'https://s4.anilist.co/file/anilistcdn/character/large/n21938-7iTMOJ4i6ET8.png', null, 10);
INSERT INTO Waifu (idWaifu, nameWaifu, nickWaifu, tierWaifu, imageURLWaifu, User_idUser, Source_idSource) VALUES (19, 'Kaguya Shinomiya', 'O kawaii koto', 1, 'https://s4.anilist.co/file/anilistcdn/character/large/b120649-CNZaUYjUvrd3.png', null, 11);
INSERT INTO Waifu (idWaifu, nameWaifu, nickWaifu, tierWaifu, imageURLWaifu, User_idUser, Source_idSource) VALUES (20, 'Chika Fujiwara', 'Baka-Chika', 1, 'https://s4.anilist.co/file/anilistcdn/character/large/b121103-DQMzOfszMFgd.png', null, 11);
INSERT INTO Waifu (idWaifu, nameWaifu, nickWaifu, tierWaifu, imageURLWaifu, User_idUser, Source_idSource) VALUES (21, 'Ai Hayasaka', null, 1, 'https://s4.anilist.co/file/anilistcdn/character/large/b121104-UTg9FVX2WS3L.png', null, 11);
INSERT INTO Waifu (idWaifu, nameWaifu, nickWaifu, tierWaifu, imageURLWaifu, User_idUser, Source_idSource) VALUES (22, 'Emilia', null, 1, 'https://s4.anilist.co/file/anilistcdn/character/large/b88572-v2KimyNuU4XZ.jpg', null, 12);
INSERT INTO Waifu (idWaifu, nameWaifu, nickWaifu, tierWaifu, imageURLWaifu, User_idUser, Source_idSource) VALUES (23, 'Ram', 'Ram-chi', 1, 'https://s4.anilist.co/file/anilistcdn/character/large/b88576-fjTlmKcRsBxS.png', null, 12);
INSERT INTO Waifu (idWaifu, nameWaifu, nickWaifu, tierWaifu, imageURLWaifu, User_idUser, Source_idSource) VALUES (24, 'Rem', 'Rem-rin', 1, 'https://s4.anilist.co/file/anilistcdn/character/large/b88575-CjdhrvYLrToO.png', null, 12);
INSERT INTO Waifu (idWaifu, nameWaifu, nickWaifu, tierWaifu, imageURLWaifu, User_idUser, Source_idSource) VALUES (25, 'Holo', 'Wise Wolf of Yoitsu', 6, 'https://s4.anilist.co/file/anilistcdn/character/large/b7373-3fPjdv9pRhZj.jpg', null, 13);
INSERT INTO Waifu (idWaifu, nameWaifu, nickWaifu, tierWaifu, imageURLWaifu, User_idUser, Source_idSource) VALUES (26, 'Shiro', null, 6, 'https://s4.anilist.co/file/anilistcdn/character/large/n82525-Le2tc8f6OQ0w.jpg', null, 14);
INSERT INTO Waifu (idWaifu, nameWaifu, nickWaifu, tierWaifu, imageURLWaifu, User_idUser, Source_idSource) VALUES (27, 'Cthuko', 'Cthulhu', 5, 'https://s4.anilist.co/file/anilistcdn/character/large/31419.jpg', null, 17);
INSERT INTO Waifu (idWaifu, nameWaifu, nickWaifu, tierWaifu, imageURLWaifu, User_idUser, Source_idSource) VALUES (28, 'Kurisu Makise', 'Christina', 3, 'https://s4.anilist.co/file/anilistcdn/character/large/b34470-iPv1JxglAfpD.png', null, 24);
INSERT INTO Waifu (idWaifu, nameWaifu, nickWaifu, tierWaifu, imageURLWaifu, User_idUser, Source_idSource) VALUES (29, 'Ichigo', 'Code:015', 3, 'https://s4.anilist.co/file/anilistcdn/character/large/b124382-bSBkjtYjJQtr.png', null, 25);

